apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ensure this namespace is created on the cluster first
namespace: default

resources:
  - ornate-core.yaml
  - ornate-landing.yaml
  - uniz-landing.yaml
