apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cluster-issuer.yaml
  - ../configmap.yaml
  - ../ornate-core.yaml
  - ../ornate.yaml
  - ../ornate-ingress.yaml
  - ../shared/secrets.yaml
