apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../cluster-issuer.yaml
  - ../configmap.yaml
  - ../secrets.yaml
  - ../redis.yaml
  - ../ornate-core.yaml
  - ../ornate.yaml
  - ../ingress.yaml
