import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getPresignedDownloadUrl } from '@/lib/r2';

export async function GET(
    request: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {
    try {
        const { id: registrationId } = await params;

        if (!registrationId) {
            return NextResponse.json({ error: 'Registration ID required' }, { status: 400 });
        }

        const registration = await prisma.registration.findUnique({
            where: { id: registrationId },
            select: {
                certificateUrl: true,
                certificateIssuedAt: true,
                studentName: true,
            },
        });

        if (!registration) {
            return NextResponse.json({ error: 'Registration not found' }, { status: 404 });
        }

        if (!registration.certificateUrl || !registration.certificateIssuedAt) {
            return NextResponse.json({ error: 'Certificate not yet issued' }, { status: 404 });
        }

        const certValue = registration.certificateUrl;

        // Case 1: already a full external URL → redirect directly
        if (certValue.startsWith('http')) {
            return NextResponse.redirect(certValue);
        }

        // Case 2: actual R2 key (not a route path) → generate presigned URL
        if (!certValue.startsWith('/')) {
            const presignedUrl = await getPresignedDownloadUrl(certValue);
            return NextResponse.redirect(presignedUrl);
        }

        // Case 3: route path like /api/certificates/download/id
        // The cert was generated by the EMS admin and stored in R2.
        // Try predictable R2 key patterns:
        const candidateKeys = [
            `certificates/${registrationId}.pdf`,
            `certificates/${registrationId}.png`,
            `certificates/${registrationId}.jpg`,
            `certificate/${registrationId}.pdf`,
            `cert/${registrationId}.pdf`,
        ];

        for (const key of candidateKeys) {
            try {
                const url = await getPresignedDownloadUrl(key);
                // getPresignedDownloadUrl doesn't verify existence — we'd need a HEAD check.
                // Return the first candidate URL and let R2 give a 404 if it doesn't exist.
                return NextResponse.redirect(url);
            } catch {
                // try next candidate
            }
        }

        return NextResponse.json(
            { error: 'Certificate file not found in storage. Contact admin.' },
            { status: 404 }
        );
    } catch (error) {
        console.error('[certificate download]', error);
        return NextResponse.json({ error: 'Failed to generate download link' }, { status: 500 });
    }
}
