apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniz-cron-service
  labels:
    app: uniz-cron-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uniz-cron-service
  template:
    metadata:
      labels:
        app: uniz-cron-service
    spec:
      containers:
        - name: cron-service
          image: uniz-cron-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3008
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: uniz-secrets
                  key: CRON_DATABASE_URL
          envFrom:
            - configMapRef:
                name: uniz-config
            - secretRef:
                name: uniz-secrets
          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: uniz-cron-service
spec:
  selector:
    app: uniz-cron-service
  ports:
    - protocol: TCP
      port: 3008
      targetPort: 3008
