apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uniz-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rguktong.in
        - uniz.rguktong.in
        - api.uniz.rguktong.in
        - ornate-core.rguktong.in
        - ornate.rguktong.in
        - landing-api.rguktong.in
      secretName: uniz-tls-cert
  rules:
    - host: rguktong.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uniz-landing
                port:
                  number: 80
    - host: uniz.rguktong.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uniz-portal
                port:
                  number: 80
    - host: api.uniz.rguktong.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uniz-gateway
                port:
                  number: 80
    - host: ornate-core.rguktong.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ornate-core
                port:
                  number: 80
    - host: ornate.rguktong.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ornate
                port:
                  number: 80
    - host: landing-api.rguktong.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uniz-landing-backend-svc
                port:
                  number: 8000
