apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-issuer.yaml
  - configmap.yaml
  - secrets.yaml
  - gateway-configmap.yaml
  - redis.yaml
  - db-ui.yaml
  - uniz-landing.yaml
  - ornate-core.yaml
  - ornate.yaml
  - ingress.yaml
images:
  - name: ornate-core:local
    newName: docker.io/library/ornate-core
    newTag: local-1772816385
