apiVersion: apps/v1
kind: Deployment
metadata:
  name: ornate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ornate
  template:
    metadata:
      labels:
        app: ornate
    spec:
      containers:
        - name: ornate
          image: ornate:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: uniz-config
            - configMapRef:
                name: ornate-config
            - secretRef:
                name: ornate-secrets
          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ornate
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: ornate
