apiVersion: v1
kind: Secret
metadata:
  name: uniz-secrets
type: Opaque
stringData:
  JWT_SECURITY_KEY: "uniz_vault_secure_2026_key"
  SMTP_PASS: "pdke hcfz fltp qagc"
  EMAIL_PASS: "pdke hcfz fltp qagc"
  # DB URLs (pointed to the Docker host for now via 172.17.0.1)
  AUTH_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=auth_v2&connection_limit=10"
  USER_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=user_v2&connection_limit=10"
  OUTPASS_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=outpass_v2&connection_limit=10"
  ACADEMICS_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=academics_v2&connection_limit=10"
  FILES_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=files_v2&connection_limit=10"
  MAIL_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=mail_v2&connection_limit=10"
  NOTIFICATION_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=notifications_v2&connection_limit=10"
  CRON_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=cron_v2&connection_limit=10"
---
apiVersion: v1
kind: Secret
metadata:
  name: ornate-ems-secrets
type: Opaque
stringData:
  # Using the same PG user/password as the rest of the app
  DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=ornate_v1&connection_limit=10"
  DIRECT_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=ornate_v1"
  NEXTAUTH_SECRET: "Jd8s/K9+2l0dJ821sQ/92+10s+234123+asdad="
  R2_ACCESS_KEY_ID: "ace0a45a23c4d231fa71f23e74631907"
  R2_SECRET_ACCESS_KEY: "8a3667d9c079990c50db6d560905a29ff0bafa8f2bf3eff7c9be4cc3c919f98d"
  AWS_ACCESS_KEY_ID: "AKIATU7FSI4NQYFJJNEH"
  AWS_SECRET_ACCESS_KEY: "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"
