apiVersion: v1
kind: Secret
metadata:
  name: uniz-secrets
type: Opaque
stringData:
  JWT_SECURITY_KEY: "uniz_vault_secure_2026_key"
  SMTP_PASS: "rllc qsdq vuxg gggl"
  EMAIL_PASS: "rllc qsdq vuxg gggl"
  # DB URLs (pointed to the Docker host for now via 172.17.0.1)
  AUTH_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=auth_v2"
  USER_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=user_v2"
  OUTPASS_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=outpass_v2"
  ACADEMICS_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=academics_v2"
  FILES_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=files_v2"
  MAIL_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=mail_v2"
  NOTIFICATION_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=notifications_v2"
  CRON_DATABASE_URL: "postgresql://user:password@172.17.0.1:5432/uniz_db?sslmode=disable&schema=cron_v2"
