apiVersion: v1
kind: Secret
metadata:
  name: uniz-secrets
type: Opaque
stringData:
  JWT_SECURITY_KEY: "${JWT_SECURITY_KEY}"
  SMTP_PASS: "${SMTP_PASS}"
  EMAIL_PASS: "${EMAIL_PASS}"
  AUTH_DATABASE_URL: "${AUTH_DATABASE_URL}"
  USER_DATABASE_URL: "${USER_DATABASE_URL}"
  OUTPASS_DATABASE_URL: "${OUTPASS_DATABASE_URL}"
  ACADEMICS_DATABASE_URL: "${ACADEMICS_DATABASE_URL}"
  FILES_DATABASE_URL: "${FILES_DATABASE_URL}"
  MAIL_DATABASE_URL: "${MAIL_DATABASE_URL}"
  NOTIFICATION_DATABASE_URL: "${NOTIFICATION_DATABASE_URL}"
  CRON_DATABASE_URL: "${CRON_DATABASE_URL}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ornate-ems-secrets
type: Opaque
stringData:
  DATABASE_URL: "${ORNATE_DATABASE_URL}"
  DIRECT_URL: "${ORNATE_DIRECT_URL}"
  NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
  R2_ACCESS_KEY_ID: "${R2_ACCESS_KEY_ID}"
  R2_SECRET_ACCESS_KEY: "${R2_SECRET_ACCESS_KEY}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
