apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniz-academics-service
  labels:
    app: uniz-academics-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uniz-academics-service
  template:
    metadata:
      labels:
        app: uniz-academics-service
    spec:
      containers:
        - name: academics-service
          image: uniz-academics-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: uniz-secrets
                  key: ACADEMICS_DATABASE_URL
          envFrom:
            - configMapRef:
                name: uniz-config
            - secretRef:
                name: uniz-secrets
          resources:
            limits:
              cpu: "1000m"
              memory: "1024Mi"
            requests:
              cpu: "50m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: uniz-academics-service
spec:
  selector:
    app: uniz-academics-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: uniz-academics-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: uniz-academics-service
  minReplicas: 3
  maxReplicas: 25
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 45
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 200
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
