apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cluster-issuer.yaml
  - ../configmap.yaml
  - ../shared/secrets.yaml
  - ../redis.yaml
  - ../ingress.yaml
  - ../academics-service.yaml
  - ../auth-service.yaml
  - ../cron-service.yaml
  - ../db-ui.yaml
  - ../files-service.yaml
  - ../gateway-api.yaml
  - ../gateway-configmap.yaml
  - ../gateway.yaml
  - ../mail-service.yaml
  - ../notification-service.yaml
  - ../outpass-service.yaml
  - ../portal.yaml
  - ../uniz-landing.yaml
  - ../user-service.yaml
  - ../cron-job.yaml
  - ../storage-cleanup-job.yaml
