
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.5.0
 * Query Engine version: 280c870be64f457428992c43c1f6d557fab6e29e
 */
Prisma.prismaVersion = {
  client: "7.5.0",
  engine: "280c870be64f457428992c43c1f6d557fab6e29e"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AdminScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  role: 'role',
  branch: 'branch',
  clubId: 'clubId',
  createdAt: 'createdAt',
  bio: 'bio',
  designation: 'designation',
  notificationSettings: 'notificationSettings',
  phone: 'phone',
  preferences: 'preferences',
  profilePicture: 'profilePicture',
  coordinatorToken: 'coordinatorToken',
  coordinatorTokenExpiry: 'coordinatorTokenExpiry'
};

exports.Prisma.AnalyticsSnapshotScalarFieldEnum = {
  id: 'id',
  snapshotDate: 'snapshotDate',
  totalOnlineRegistrations: 'totalOnlineRegistrations',
  totalOfflineRegistrations: 'totalOfflineRegistrations',
  totalAttendance: 'totalAttendance',
  totalRevenue: 'totalRevenue',
  avgAttendanceRate: 'avgAttendanceRate',
  totalEvents: 'totalEvents',
  createdAt: 'createdAt',
  activeParticipants: 'activeParticipants',
  cancelledRegistrations: 'cancelledRegistrations',
  completionRate: 'completionRate',
  confirmedRegistrations: 'confirmedRegistrations',
  pendingRegistrations: 'pendingRegistrations',
  pendingRevenue: 'pendingRevenue',
  waitlistRegistrations: 'waitlistRegistrations'
};

exports.Prisma.AnnouncementScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  category: 'category',
  isPinned: 'isPinned',
  targetAudience: 'targetAudience',
  expiryDate: 'expiryDate',
  status: 'status',
  viewCount: 'viewCount',
  creatorId: 'creatorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  action: 'action',
  entityType: 'entityType',
  entityId: 'entityId',
  metadata: 'metadata',
  performedBy: 'performedBy',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  timestamp: 'timestamp'
};

exports.Prisma.BestOutgoingStudentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  rollNumber: 'rollNumber',
  photo: 'photo',
  branch: 'branch',
  year: 'year',
  cgpa: 'cgpa',
  achievements: 'achievements',
  placementStatus: 'placementStatus',
  company: 'company',
  package: 'package',
  gender: 'gender',
  awardYear: 'awardYear',
  isPublished: 'isPublished',
  isOverall: 'isOverall',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  creatorId: 'creatorId'
};

exports.Prisma.BranchPointsScalarFieldEnum = {
  id: 'id',
  sportId: 'sportId',
  branch: 'branch',
  points: 'points',
  manualAdjustment: 'manualAdjustment',
  adjustmentReason: 'adjustmentReason'
};

exports.Prisma.BrandLogoScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  format: 'format',
  size: 'size',
  dimensions: 'dimensions',
  url: 'url',
  status: 'status',
  uploadDate: 'uploadDate',
  thumbnail: 'thumbnail',
  creatorId: 'creatorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CertificateThemeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  preview: 'preview',
  colors: 'colors',
  style: 'style',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EventScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  date: 'date',
  venue: 'venue',
  category: 'category',
  creatorId: 'creatorId',
  posterUrl: 'posterUrl',
  additionalImages: 'additionalImages',
  registrationOpen: 'registrationOpen',
  fee: 'fee',
  price: 'price',
  maxCapacity: 'maxCapacity',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  certificateIssuedAt: 'certificateIssuedAt',
  certificateStatus: 'certificateStatus',
  certificateTemplates: 'certificateTemplates',
  certificateTheme: 'certificateTheme',
  customFields: 'customFields',
  documents: 'documents',
  eligibility: 'eligibility',
  endDate: 'endDate',
  endTime: 'endTime',
  eventType: 'eventType',
  locationType: 'locationType',
  minParticipants: 'minParticipants',
  prizes: 'prizes',
  rules: 'rules',
  shortDescription: 'shortDescription',
  startTime: 'startTime',
  teamSizeMax: 'teamSizeMax',
  teamSizeMin: 'teamSizeMin',
  time: 'time',
  waitlistEnabled: 'waitlistEnabled',
  paymentGateway: 'paymentGateway',
  status: 'status'
};

exports.Prisma.FestSettingsScalarFieldEnum = {
  id: 'id',
  festName: 'festName',
  tagline: 'tagline',
  logoUrl: 'logoUrl',
  brochureUrl: 'brochureUrl',
  description: 'description',
  startDate: 'startDate',
  endDate: 'endDate',
  venue: 'venue',
  registrationOpen: 'registrationOpen',
  maintenanceMode: 'maintenanceMode',
  guestRegistration: 'guestRegistration',
  emailNotifications: 'emailNotifications',
  instagramUrl: 'instagramUrl',
  youtubeUrl: 'youtubeUrl',
  supportEmail: 'supportEmail',
  updatedAt: 'updatedAt'
};

exports.Prisma.GalleryAlbumScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  coverImage: 'coverImage',
  creatorId: 'creatorId',
  tags: 'tags',
  isArchived: 'isArchived',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GalleryImageScalarFieldEnum = {
  id: 'id',
  url: 'url',
  caption: 'caption',
  albumId: 'albumId',
  uploadedAt: 'uploadedAt'
};

exports.Prisma.MatchScalarFieldEnum = {
  id: 'id',
  round: 'round',
  matchId: 'matchId',
  team1Id: 'team1Id',
  team1Name: 'team1Name',
  team2Id: 'team2Id',
  team2Name: 'team2Name',
  time: 'time',
  venue: 'venue',
  score1: 'score1',
  score2: 'score2',
  note: 'note',
  referee: 'referee',
  matchOrder: 'matchOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  sportId: 'sportId',
  date: 'date',
  status: 'status',
  winner: 'winner'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  senderId: 'senderId',
  senderName: 'senderName',
  senderRole: 'senderRole',
  senderBranch: 'senderBranch',
  recipientId: 'recipientId',
  recipientName: 'recipientName',
  recipientRole: 'recipientRole',
  message: 'message',
  isRead: 'isRead',
  isStarred: 'isStarred',
  isArchived: 'isArchived',
  priority: 'priority',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PromoVideoScalarFieldEnum = {
  id: 'id',
  title: 'title',
  url: 'url',
  platform: 'platform',
  thumbnail: 'thumbnail',
  status: 'status',
  views: 'views',
  duration: 'duration',
  uploadDate: 'uploadDate',
  creatorId: 'creatorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  category: 'category'
};

exports.Prisma.RegistrationScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  userId: 'userId',
  studentName: 'studentName',
  studentId: 'studentId',
  status: 'status',
  paymentStatus: 'paymentStatus',
  amount: 'amount',
  transactionId: 'transactionId',
  screenshotUrl: 'screenshotUrl',
  createdAt: 'createdAt',
  certificateIssuedAt: 'certificateIssuedAt',
  certificateType: 'certificateType',
  certificateUrl: 'certificateUrl',
  rank: 'rank',
  email: 'email',
  phone: 'phone',
  branch: 'branch',
  year: 'year',
  section: 'section'
};

exports.Prisma.SportScalarFieldEnum = {
  id: 'id',
  name: 'name',
  gender: 'gender',
  category: 'category',
  format: 'format',
  status: 'status',
  description: 'description',
  icon: 'icon',
  bannerUrl: 'bannerUrl',
  winnerPoints: 'winnerPoints',
  runnerUpPoints: 'runnerUpPoints',
  participationPoints: 'participationPoints',
  awards: 'awards',
  maxTeamsPerBranch: 'maxTeamsPerBranch',
  minPlayersPerTeam: 'minPlayersPerTeam',
  maxPlayersPerTeam: 'maxPlayersPerTeam',
  rules: 'rules',
  eligibility: 'eligibility',
  registrationDeadline: 'registrationDeadline',
  matchDuration: 'matchDuration',
  certificateStatus: 'certificateStatus',
  certificateIssuedAt: 'certificateIssuedAt',
  certificateTheme: 'certificateTheme',
  certificateTemplates: 'certificateTemplates',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SportRegistrationScalarFieldEnum = {
  id: 'id',
  sportId: 'sportId',
  studentName: 'studentName',
  studentId: 'studentId',
  email: 'email',
  phone: 'phone',
  branch: 'branch',
  year: 'year',
  section: 'section',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.SportTeamScalarFieldEnum = {
  id: 'id',
  sportId: 'sportId',
  teamId: 'teamId',
  createdAt: 'createdAt'
};

exports.Prisma.SportWinnerAnnouncementScalarFieldEnum = {
  id: 'id',
  sportId: 'sportId',
  isPublished: 'isPublished',
  publishedAt: 'publishedAt',
  positions: 'positions',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StallScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  owner: 'owner',
  bidAmount: 'bidAmount',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  description: 'description',
  price: 'price',
  stallNo: 'stallNo',
  teamSize: 'teamSize'
};

exports.Prisma.TaskScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  date: 'date',
  time: 'time',
  assignedTo: 'assignedTo',
  priority: 'priority',
  status: 'status',
  creatorId: 'creatorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  teamName: 'teamName',
  teamCode: 'teamCode',
  eventId: 'eventId',
  leaderId: 'leaderId',
  leaderName: 'leaderName',
  leaderEmail: 'leaderEmail',
  leaderPhone: 'leaderPhone',
  status: 'status',
  paymentStatus: 'paymentStatus',
  amount: 'amount',
  transactionId: 'transactionId',
  screenshotUrl: 'screenshotUrl',
  registrationId: 'registrationId',
  isLocked: 'isLocked',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamMemberScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  userId: 'userId',
  name: 'name',
  email: 'email',
  phone: 'phone',
  rollNumber: 'rollNumber',
  department: 'department',
  year: 'year',
  section: 'section',
  role: 'role',
  status: 'status',
  joinedAt: 'joinedAt',
  sportRegistrationId: 'sportRegistrationId'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  role: 'role',
  branch: 'branch',
  currentYear: 'currentYear',
  phone: 'phone',
  createdAt: 'createdAt',
  stdid: 'stdid'
};

exports.Prisma.WinnerAnnouncementScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  isPublished: 'isPublished',
  publishedAt: 'publishedAt',
  positions: 'positions',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.UserRole = exports.$Enums.UserRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  BRANCH_ADMIN: 'BRANCH_ADMIN',
  CLUB_COORDINATOR: 'CLUB_COORDINATOR',
  SPORTS_ADMIN: 'SPORTS_ADMIN',
  HHO: 'HHO',
  STUDENT: 'STUDENT',
  EVENT_COORDINATOR: 'EVENT_COORDINATOR',
  BRANCH_SPORTS_ADMIN: 'BRANCH_SPORTS_ADMIN'
};

exports.EventStatus = exports.$Enums.EventStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

exports.MatchStatus = exports.$Enums.MatchStatus = {
  PENDING: 'PENDING',
  SCHEDULED: 'SCHEDULED',
  LIVE: 'LIVE',
  COMPLETED: 'COMPLETED'
};

exports.MatchWinner = exports.$Enums.MatchWinner = {
  TEAM1: 'TEAM1',
  TEAM2: 'TEAM2',
  DRAW: 'DRAW'
};

exports.RegistrationStatus = exports.$Enums.RegistrationStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  WAITLISTED: 'WAITLISTED',
  ATTENDED: 'ATTENDED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED'
};

exports.SportGender = exports.$Enums.SportGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  MIXED: 'MIXED'
};

exports.SportCategory = exports.$Enums.SportCategory = {
  INDIVIDUAL: 'INDIVIDUAL',
  TEAM: 'TEAM'
};

exports.SportFormat = exports.$Enums.SportFormat = {
  KNOCKOUT: 'KNOCKOUT',
  LEAGUE: 'LEAGUE',
  GROUP_KNOCKOUT: 'GROUP_KNOCKOUT'
};

exports.SportStatus = exports.$Enums.SportStatus = {
  UPCOMING: 'UPCOMING',
  REGISTRATION_OPEN: 'REGISTRATION_OPEN',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED'
};

exports.TeamRole = exports.$Enums.TeamRole = {
  LEADER: 'LEADER',
  MEMBER: 'MEMBER',
  VICE_CAPTAIN: 'VICE_CAPTAIN'
};

exports.MemberStatus = exports.$Enums.MemberStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED'
};

exports.Prisma.ModelName = {
  Admin: 'Admin',
  AnalyticsSnapshot: 'AnalyticsSnapshot',
  Announcement: 'Announcement',
  AuditLog: 'AuditLog',
  BestOutgoingStudent: 'BestOutgoingStudent',
  BranchPoints: 'BranchPoints',
  BrandLogo: 'BrandLogo',
  CertificateTheme: 'CertificateTheme',
  Event: 'Event',
  FestSettings: 'FestSettings',
  GalleryAlbum: 'GalleryAlbum',
  GalleryImage: 'GalleryImage',
  Match: 'Match',
  Notification: 'Notification',
  PromoVideo: 'PromoVideo',
  Registration: 'Registration',
  Sport: 'Sport',
  SportRegistration: 'SportRegistration',
  SportTeam: 'SportTeam',
  SportWinnerAnnouncement: 'SportWinnerAnnouncement',
  Stall: 'Stall',
  Task: 'Task',
  Team: 'Team',
  TeamMember: 'TeamMember',
  User: 'User',
  WinnerAnnouncement: 'WinnerAnnouncement'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
