services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: ornate-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - REDIS_URL=redis://redis:6379
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_ENDPOINT=${R2_ENDPOINT}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_DOMAIN=${R2_PUBLIC_DOMAIN}
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    container_name: ornate-worker
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_SUBJECT=${VAPID_SUBJECT}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: ornate-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
