export const STALLS = [
  {
    id: "smoke-biscuits",
    name: "Smoke Biscuits",
    no: "14",
    team: "40",
    price: "9K",
    description:
      "Flash-frozen nitrogen treats that release cosmic vapor with every bite.",
    type: "dessert",
  },
  {
    id: "pani-puri",
    name: "Pani Puri",
    no: "16",
    team: "80",
    price: "50K",
    description: "Sphere-shaped pods filled with spicy interstellar nectar.",
    type: "food",
  },
  {
    id: "chia-stall",
    name: "Chia Stall",
    no: "17",
    team: "38",
    price: "15K",
    description: "Hydrating super-seeds from the bio-domes of Sector 7.",
    type: "cafe",
  },
  {
    id: "chinese-food-court",
    name: "Chinese Food Court",
    no: "02",
    team: "32",
    price: "25.5K",
    description: "Stir-fried gravity noodles and plasma-seared wontons.",
    type: "food",
  },
  {
    id: "chicken-lollipops",
    name: "Chicken Lollipops",
    no: "06",
    team: "29",
    price: "6.5K",
    description: "Protein spikes glazed in spicy Martian dust.",
    type: "food",
  },
  {
    id: "bread-items",
    name: "Bread Items",
    no: "07",
    team: "37",
    price: "9.5K",
    description: "Zero-G baked loaves and orbital pastries.",
    type: "food",
  },
  {
    id: "photo-booth",
    name: "Photo Booth",
    no: "24",
    team: "17",
    price: "19.5K",
    description: "Capture your holographic essence against cosmic backdrops.",
    type: "lifestyle",
  },
  {
    id: "sweets-ice-creams",
    name: "Sweets & Ice Creams",
    no: "08",
    team: "27",
    price: "50K",
    description: "Sugar crystals and cryogenic creams from the icy moons.",
    type: "dessert",
  },
  {
    id: "cool-drinks",
    name: "Cool Drinks",
    no: "09",
    team: "16",
    price: "84K",
    description: "Chilled liquid fuel to keep your systems operational.",
    type: "cafe",
  },
  {
    id: "waffles",
    name: "Waffles",
    no: "18",
    team: "11",
    price: "30K",
    description: "Grid-patterned delicacies drizzled with stellar honey.",
    type: "dessert",
  },
  {
    id: "fruits-juices",
    name: "Fruits & Juices",
    no: "10",
    team: "02",
    price: "20K",
    description: "Freshly harvested organics from the orbital greenhouses.",
    type: "food",
  },
  {
    id: "gift-stall",
    name: "Gift Stall",
    no: "20",
    team: "06",
    price: "5.5K",
    description: "Memorabilia and artifacts from the great expanse.",
    type: "lifestyle",
  },
  {
    id: "t-shirts",
    name: "T-Shirts",
    no: "25",
    team: "09",
    price: "4K",
    description: "Limited edition threads featuring Sector Ornate insignias.",
    type: "lifestyle",
  },
  {
    id: "biryani",
    name: "Biryani",
    no: "05",
    team: "31",
    price: "72K",
    description: "Layered rice and spice fusion, the heart of the galaxy.",
    type: "food",
  },
  {
    id: "soda-badam-milks",
    name: "Soda & Badam Milks",
    no: "13",
    team: "05",
    price: "55K",
    description: "Fizzy bursts and creamy almond transmissions.",
    type: "cafe",
  },
  {
    id: "pulka-paratha",
    name: "Pulka & Paratha",
    no: "04",
    team: "03",
    price: "28K",
    description: "Hand-stretched dough discs, seared in the thermal forge.",
    type: "food",
  },
  {
    id: "momos",
    name: "Momos",
    no: "11",
    team: "23",
    price: "9K",
    description: "Steamed nutrient pockets from the high-altitude stations.",
    type: "food",
  },
  {
    id: "dosa",
    name: "Dosa",
    no: "01",
    team: "36",
    price: "54K",
    description: "Crispy fermented crepes, a morning tradition in the base.",
    type: "food",
  },
  {
    id: "french-fries",
    name: "French Fries",
    no: "15",
    team: "20",
    price: "15K",
    description: "Salt-cured potato batons, the ultimate ship snack.",
    type: "food",
  },
  {
    id: "mehandi-tattoos",
    name: "Mehandi & Tattoos",
    no: "22",
    team: "--",
    price: "--",
    description: "Biological ink patterns and permanent cybernetic markups.",
    type: "lifestyle",
  },
  {
    id: "tiffins",
    name: "Tiffins",
    no: "03",
    team: "30",
    price: "21K",
    description: "Quick-access nutrient containers for busy flight crews.",
    type: "food",
  },
  {
    id: "cotton-candy",
    name: "Cotton Candy",
    no: "23",
    team: "12",
    price: "5K",
    description: "Woven sugar clouds that melt into the void.",
    type: "dessert",
  },
  {
    id: "mmm",
    name: "MMM",
    no: "21",
    team: "25",
    price: "39K",
    description: "Maximum Mars Munchies - a triple-layered flavor blast.",
    type: "food",
  },
  {
    id: "sea-starters",
    name: "Sea Starters",
    no: "12",
    team: "26",
    price: "8K",
    description: "Oceanic harvests from the water worlds of Proxima.",
    type: "food",
  },
  {
    id: "juke-box",
    name: "Juke Box",
    no: "--",
    team: "HHO",
    price: "--",
    description: "Sonic waves and acoustic transmissions for the sector.",
    type: "lifestyle",
  },
];
